import fs from 'fs';
import path from 'path';

/**
 * Compiles the reviewed gate matrix into a TypeScript module.
 *
 * The map is generated rather than read from CSV at runtime so the server has
 * no dependency on a docs/ file being present and correctly resolved from
 * whatever directory it was started in — a deployment could otherwise silently
 * lose every route mapping and fall back to legacy checks without anyone
 * noticing.
 */
const csvPath = path.join(__dirname, '..', '..', '..', 'docs', 'superpowers', 'plans', 'gate-matrix.csv');
const outPath = path.join(__dirname, '..', 'permissions', 'route-permissions.ts');

const rows = fs
  .readFileSync(csvPath, 'utf8')
  .trim()
  .split('\n')
  .slice(1)
  .map((line) => {
    const [method, route, module, action, roles, lineNo, gate] = line.split(',');
    return { method, route, module, action, gate, line: lineNo };
  })
  .filter((r) => r.gate !== 'none');

const entries = rows
  .map((r) => `  '${r.method} ${r.route}': { module: '${r.module}', action: '${r.action}' },`)
  .join('\n');

const source = `/**
 * Route to permission map. GENERATED by scripts/generate-route-map.ts from
 * docs/superpowers/plans/gate-matrix.csv — do not edit by hand.
 *
 * Regenerate with: npm run authz:routemap
 *
 * ${rows.length} gated routes.
 */

export interface RoutePermission {
  module: string;
  action: string;
}

export const ROUTE_PERMISSIONS: Readonly<Record<string, RoutePermission>> = {
${entries}
};

export function lookupRoutePermission(
  method: string,
  routePath: string,
): RoutePermission | undefined {
  return ROUTE_PERMISSIONS[\`\${method.toUpperCase()} \${routePath}\`];
}
`;

fs.writeFileSync(outPath, source);
process.stderr.write(`route-permissions.ts written: ${rows.length} routes\n`);
