'use client';

import { format } from 'date-fns';
import { QRCodeSVG } from 'qrcode.react';
import type { Company } from '@/modules/companies/types';
import type { Client, Invoice, InvoiceTemplate, InvoiceColumn, InvoiceLineItem } from '../types';
import { CurrencyAmount } from '@/lib/currency';
import { publicInvoiceUrl } from '@/services/publicService';

const DEFAULT_COLUMNS: InvoiceColumn[] = [
  { id: 'description', key: 'description', label: 'Description', visible: true, width: 55, align: 'left' },
  { id: 'quantity', key: 'quantity', label: 'Qty', visible: true, width: 15, align: 'right' },
  { id: 'unitPrice', key: 'unitPrice', label: 'Unit', visible: true, width: 15, align: 'right' },
  { id: 'amount', key: 'amount', label: 'Amount', visible: true, width: 15, align: 'right' },
];

const alignClass: Record<string, string> = { left: 'text-left', center: 'text-center', right: 'text-right' };

interface InvoiceDocumentProps {
  invoice: Invoice;
  client?: Client;
  company?: Company | null;
  template?: InvoiceTemplate;
}

const fallbackTemplate: Pick<
  InvoiceTemplate,
  | 'name'
  | 'layout'
  | 'primaryColor'
  | 'accentColor'
  | 'showCompanyAddress'
  | 'showTaxId'
  | 'paymentInstructions'
  | 'terms'
  | 'footerNote'
> = {
  name: 'Default',
  layout: 'classic',
  primaryColor: '#111827',
  accentColor: '#2563eb',
  showCompanyAddress: true,
  showTaxId: false,
  paymentInstructions: 'Payment is due within 30 days.',
  terms: 'Thank you for your business.',
  footerNote: 'Generated by TaskFlow',
};

export function InvoiceDocument({ invoice, client, company, template }: InvoiceDocumentProps) {
  const activeTemplate = { ...fallbackTemplate, ...template };
  const subtotal = invoice.lineItems.reduce((sum, item) => sum + item.amount, 0);
  const taxRate = invoice.taxRate || 0;
  const taxAmount = Number((subtotal * (taxRate / 100)).toFixed(2));
  const total = invoice.total || subtotal + taxAmount;
  const compact = activeTemplate.layout === 'compact';
  const modern = activeTemplate.layout === 'modern';
  const letterhead = activeTemplate.layout === 'letterhead';
  const amount = (value: number) => <CurrencyAmount value={value} currencyCode={invoice.currency || 'USD'} />;

  const columns = (template?.columns?.length ? template.columns : DEFAULT_COLUMNS).filter((c) => c.visible);
  const cellValue = (col: InvoiceColumn, line: InvoiceLineItem) => {
    switch (col.key) {
      case 'sku': return line.sku ?? '';
      case 'description': return line.description;
      case 'quantity': return line.quantity;
      case 'unitPrice': return amount(line.unitPrice);
      case 'amount': return amount(line.amount);
      case 'custom': return line.custom?.[col.id] ?? '';
      default: return '';
    }
  };
  const bankAccounts = (template?.bankAccounts ?? []).filter(
    (b) => b.bankName || b.accountHolder || b.accountNumber || b.iban || b.swift,
  );

  // Sections the template marks to start on a fresh printed page.
  const sectionBreaks = new Set<string>(template?.sectionBreaks ?? []);
  const pb = (id: string) => (sectionBreaks.has(id) ? 'invoice-page-break ' : '');
  const pbMark = (id: string) =>
    sectionBreaks.has(id) ? (
      <div className="my-5 flex items-center gap-2 text-[10px] uppercase tracking-wide text-slate-400 print:hidden">
        <div className="h-px flex-1 border-t border-dashed border-slate-300" />
        Page break
        <div className="h-px flex-1 border-t border-dashed border-slate-300" />
      </div>
    ) : null;
  const splitPaymentTerms = sectionBreaks.has('payment') || sectionBreaks.has('terms');

  return (
    <div
      className="invoice-print-area relative mx-auto min-h-[760px] w-full rounded-sm bg-white text-slate-950 shadow-sm"
      style={{
        borderTop: letterhead ? `10px solid ${activeTemplate.primaryColor}` : undefined,
        backgroundImage: template?.letterheadPdfUrl
          ? `linear-gradient(rgba(255,255,255,0.86), rgba(255,255,255,0.86)), url("${template.letterheadPdfUrl}")`
          : undefined,
        backgroundSize: 'cover',
        backgroundPosition: 'center top',
      }}
    >
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 10mm;
          }
          html,
          body {
            margin: 0 !important;
            padding: 0 !important;
            background: white !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .invoice-print-area {
            width: 100% !important;
            max-width: none !important;
            margin: 0 !important;
            box-shadow: none !important;
            border-radius: 0 !important;
            overflow: visible !important;
            min-height: auto !important;
          }
          .invoice-preview-actions, .no-print {
            display: none !important;
          }
          .invoice-line-items {
            width: 100% !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            page-break-inside: auto !important;
          }
          .invoice-line-items thead {
            display: table-header-group !important;
          }
          .invoice-line-items tfoot {
            display: table-footer-group !important;
          }
          .invoice-line-items tr {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
            page-break-after: auto !important;
          }
          .invoice-line-items td,
          .invoice-line-items th {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
          }
          .invoice-line-items th {
            color: #111827 !important;
            background: #f3f4f6 !important;
            border-bottom: 1px solid #d1d5db !important;
          }
          .invoice-line-items td {
            border-bottom: 1px solid #e5e7eb !important;
          }
          .invoice-totals {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
          }
          /* CSS grid containers do not fragment across printed pages in most
             engines, so long content (terms, payment) gets stuck on one page.
             Flow these as single-column blocks while printing so they paginate. */
          .invoice-flow-block {
            display: block !important;
          }
          .invoice-flow-block > * + * {
            margin-top: 1.5rem !important;
          }
          .invoice-flow-block,
          .invoice-flow-block * {
            break-inside: auto !important;
            page-break-inside: auto !important;
          }
          /* Sections the template pushes onto their own page. */
          .invoice-page-break {
            break-before: page !important;
            page-break-before: always !important;
          }
        }
      `}</style>

      {activeTemplate.watermarkEnabled && activeTemplate.watermarkText && (
        <div className="pointer-events-none absolute inset-0 z-10 flex items-center justify-center">
          <span
            className="select-none text-8xl font-extrabold uppercase"
            style={{
              color: activeTemplate.primaryColor,
              opacity: activeTemplate.watermarkOpacity ?? 0.12,
              transform: 'rotate(-30deg)',
            }}
          >
            {activeTemplate.watermarkText}
          </span>
        </div>
      )}

      {template?.headerImageUrl && (
        <img src={template.headerImageUrl} alt="" className="h-20 w-full object-cover" />
      )}

      {/* Letterhead band: tall, centered logo */}
      {letterhead && (
        <div
          className="relative z-20 flex flex-col items-center justify-center gap-3 px-10 pb-8 pt-14"
          style={{ borderBottom: `2px solid ${activeTemplate.primaryColor}` }}
        >
          {template?.logoUrl ? (
            <img src={template.logoUrl} alt="" className="h-28 max-w-[280px] object-contain" />
          ) : (
            <div
              className="flex h-24 w-24 items-center justify-center rounded-full text-2xl font-bold text-white"
              style={{ backgroundColor: activeTemplate.primaryColor }}
            >
              {(company?.name || 'CO').slice(0, 2).toUpperCase()}
            </div>
          )}
          <div className="text-center">
            <div className="text-xl font-bold" style={{ color: activeTemplate.primaryColor }}>
              {company?.name || 'Company'}
            </div>
            {activeTemplate.showCompanyAddress && company?.address && (
              <div className="mt-1 whitespace-pre-line text-sm text-slate-500">{company.address}</div>
            )}
          </div>
        </div>
      )}

      <div className={`${compact ? 'p-8' : 'p-10'} relative z-20`}>
        <div
          className={`flex gap-6 ${
            modern ? 'items-start justify-between border-b pb-8' : 'items-start justify-between'
          }`}
          style={{ borderColor: activeTemplate.accentColor }}
        >
          {!letterhead && (
          <div className="min-w-0">
            {template?.logoUrl ? (
              <img
                src={template.logoUrl}
                alt=""
                className="mb-4 h-14 max-w-44 object-contain object-left"
              />
            ) : (
              <div
                className="mb-4 flex h-14 w-40 items-center justify-center rounded border text-sm font-semibold"
                style={{ borderColor: activeTemplate.accentColor, color: activeTemplate.primaryColor }}
              >
                LOGO
              </div>
            )}
            <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
              {company?.name || 'Company'}
            </div>
            {activeTemplate.showCompanyAddress && (
              <div className="mt-1 whitespace-pre-line text-sm text-slate-500">
                {company?.address || 'Company address'}
              </div>
            )}
            {activeTemplate.showTaxId && (
              <div className="mt-1 text-sm text-slate-500">Tax ID</div>
            )}
          </div>
          )}

          <div
            className={modern ? 'rounded-sm px-5 py-4 text-right text-white' : 'text-right'}
            style={modern ? { backgroundColor: activeTemplate.primaryColor } : undefined}
          >
            <div
              className="text-3xl font-bold tracking-normal"
              style={modern ? undefined : { color: activeTemplate.primaryColor }}
            >
              INVOICE
            </div>
            <div className={modern ? 'mt-2 text-sm text-white/85' : 'mt-2 text-sm text-slate-500'}>
              {invoice.invoiceNumber}
            </div>
            <div className={modern ? 'mt-1 text-sm text-white/85' : 'mt-1 text-sm text-slate-500'}>
              {invoice.status}
            </div>
          </div>
        </div>

        {pbMark('billing')}
        <div className={`${pb('billing')}grid gap-6 ${compact ? 'mt-8 grid-cols-3 text-sm' : 'mt-10 grid-cols-2'}`}>
          <div>
            <div className="text-xs font-semibold uppercase text-slate-400">Bill To</div>
            <div className="mt-2 font-semibold">{client?.name || 'Client'}</div>
            <div className="mt-1 whitespace-pre-line text-sm text-slate-500">
              {client?.address || 'Client address'}
            </div>
            {client?.email && <div className="mt-1 text-sm text-slate-500">{client.email}</div>}
          </div>
          <div className={compact ? 'text-left' : 'text-right'}>
            <div className="grid gap-1 text-sm">
              <div>
                <span className="text-slate-500">Issue date: </span>
                <span className="font-medium">{format(invoice.issueDate, 'MMM d, yyyy')}</span>
              </div>
              <div>
                <span className="text-slate-500">Due date: </span>
                <span className="font-medium">{format(invoice.dueDate, 'MMM d, yyyy')}</span>
              </div>
              <div>
                <span className="text-slate-500">Currency: </span>
                <span className="font-medium">{invoice.currency || 'USD'}</span>
              </div>
            </div>
          </div>
          {compact && (
            <div>
              <div className="text-xs font-semibold uppercase text-slate-400">Terms</div>
              <div className="mt-2 text-sm text-slate-600">
                {activeTemplate.terms || 'Standard payment terms apply.'}
              </div>
            </div>
          )}
        </div>

        {pbMark('items')}
        <div className={`${pb('items')}${compact ? 'mt-8' : 'mt-10'}`}>
          <table className="invoice-line-items w-full border-collapse text-sm">
            <colgroup>
              {columns.map((col) => (
                <col key={col.id} style={col.width ? { width: `${col.width}%` } : undefined} />
              ))}
            </colgroup>
            <thead>
              <tr className="text-white" style={{ backgroundColor: activeTemplate.primaryColor }}>
                {columns.map((col, i) => (
                  <th
                    key={col.id}
                    className={`px-4 py-3 font-semibold ${alignClass[col.align || (col.key === 'description' || col.key === 'sku' ? 'left' : 'right')]} ${i === 0 ? 'rounded-tl' : ''} ${i === columns.length - 1 ? 'rounded-tr' : ''}`}
                  >
                    {col.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {invoice.lineItems.map((line, index) => (
                <tr
                  key={`${line.description}-${index}`}
                  className={index % 2 === 0 ? 'bg-white' : 'bg-slate-50'}
                >
                  {columns.map((col, i) => (
                    <td
                      key={col.id}
                      className={`border-b px-4 py-3 ${i === 0 ? 'border-x' : ''} ${i === columns.length - 1 ? 'border-r' : ''} ${alignClass[col.align || (col.key === 'description' || col.key === 'sku' ? 'left' : 'right')]} ${col.key === 'amount' ? 'font-medium' : ''}`}
                    >
                      {cellValue(col, line)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="invoice-totals mt-8 flex justify-end">
          <div className="w-full max-w-xs space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-slate-500">Subtotal</span>
              <span>{amount(subtotal)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">Tax {taxRate.toFixed(2)}%</span>
              <span>{amount(taxAmount)}</span>
            </div>
            <div
              className="flex justify-between border-t pt-3 text-lg font-bold"
              style={{ borderColor: activeTemplate.accentColor, color: activeTemplate.primaryColor }}
            >
              <span>Total</span>
              <span>{amount(total)}</span>
            </div>
          </div>
        </div>

        {!compact && (() => {
          const paymentInner = (
            <>
              <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
                Payment
              </div>
              {activeTemplate.paymentInstructions && (
                <p className="mt-2 text-slate-600">{activeTemplate.paymentInstructions}</p>
              )}
              {bankAccounts.length > 0 && (
                <div className="mt-3 space-y-3">
                  {bankAccounts.map((bank) => (
                    <div key={bank.id} className="rounded border border-slate-200 p-3">
                      {bank.bankName && (
                        <div className="font-medium text-slate-700">{bank.bankName}{bank.currency ? ` · ${bank.currency}` : ''}</div>
                      )}
                      <div className="mt-1 grid gap-0.5 text-xs text-slate-600">
                        {bank.accountHolder && <div><span className="text-slate-400">Account holder: </span>{bank.accountHolder}</div>}
                        {bank.accountNumber && <div><span className="text-slate-400">Account no.: </span>{bank.accountNumber}</div>}
                        {bank.iban && <div><span className="text-slate-400">IBAN: </span>{bank.iban}</div>}
                        {bank.swift && <div><span className="text-slate-400">SWIFT/BIC: </span>{bank.swift}</div>}
                      </div>
                    </div>
                  ))}
                </div>
              )}
              {!activeTemplate.paymentInstructions && bankAccounts.length === 0 && (
                <p className="mt-2 text-slate-600">Payment instructions will appear here.</p>
              )}
            </>
          );
          const termsInner = (
            <>
              <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
                Terms
              </div>
              <p className="mt-2 text-slate-600">
                {activeTemplate.terms || 'Terms and conditions will appear here.'}
              </p>
            </>
          );
          // Keep the side-by-side layout unless either section is pushed to its
          // own page, in which case render them as separate stacked sections.
          if (!splitPaymentTerms) {
            return (
              <div className="invoice-flow-block mt-10 grid gap-6 text-sm md:grid-cols-2">
                <div>{paymentInner}</div>
                <div>{termsInner}</div>
              </div>
            );
          }
          return (
            <>
              {pbMark('payment')}
              <div className={`${pb('payment')}mt-10 text-sm`}>{paymentInner}</div>
              {pbMark('terms')}
              <div className={`${pb('terms')}mt-8 text-sm`}>{termsInner}</div>
            </>
          );
        })()}

        {invoice.notes && (
          <>
            {pbMark('notes')}
            <div className={`${pb('notes')}mt-8 rounded border p-4 text-sm text-slate-600`}>
              <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
                Notes
              </div>
              <p className="mt-2">{invoice.notes}</p>
            </div>
          </>
        )}

        {(template?.stampUrl || template?.signatureUrl) && (
          <>
          {pbMark('signature')}
          <div className={`${pb('signature')}mt-10 flex items-end justify-end gap-12`}>
            {template?.stampUrl && (
              <img src={template.stampUrl} alt="" className="h-24 w-24 object-contain" />
            )}
            {template?.signatureUrl && (
              <div className="text-center">
                <img src={template.signatureUrl} alt="" className="mx-auto h-16 object-contain" />
                <div className="mt-1 border-t border-slate-300 pt-1 text-xs text-slate-500">
                  {template?.signatureLabel || 'Authorized signature'}
                </div>
              </div>
            )}
          </div>
          </>
        )}

        {(template?.qrEnabled ?? true) && (
          <>
          {pbMark('qr')}
          <div
            className={`${pb('qr')}mt-8 flex ${
              (template?.qrPosition ?? 'center') === 'center'
                ? 'justify-center'
                : (template?.qrPosition ?? 'center') === 'right'
                  ? 'justify-end'
                  : 'justify-start'
            }`}
          >
            <div className="text-center">
              <QRCodeSVG value={publicInvoiceUrl(invoice.id)} size={92} level="M" />
              <div className="mt-1 text-[10px] text-slate-400">Scan to view &amp; download</div>
            </div>
          </div>
          </>
        )}

        <div className="mt-6 border-t pt-4 text-center text-xs text-slate-500">
          {activeTemplate.footerNote || 'Footer note appears here.'}
        </div>
      </div>

      {template?.footerImageUrl && (
        <img src={template.footerImageUrl} alt="" className="h-16 w-full object-cover" />
      )}
    </div>
  );
}
