'use client';

import { format } from 'date-fns';
import type { Company } from '@/modules/companies/types';
import type { Client, Invoice, InvoiceTemplate } from '../types';
import { CurrencyAmount } from '@/lib/currency';

interface InvoiceDocumentProps {
  invoice: Invoice;
  client?: Client;
  company?: Company | null;
  template?: InvoiceTemplate;
}

const fallbackTemplate: Pick<
  InvoiceTemplate,
  | 'name'
  | 'layout'
  | 'primaryColor'
  | 'accentColor'
  | 'showCompanyAddress'
  | 'showTaxId'
  | 'paymentInstructions'
  | 'terms'
  | 'footerNote'
> = {
  name: 'Default',
  layout: 'classic',
  primaryColor: '#111827',
  accentColor: '#2563eb',
  showCompanyAddress: true,
  showTaxId: false,
  paymentInstructions: 'Payment is due within 30 days.',
  terms: 'Thank you for your business.',
  footerNote: 'Generated by TaskFlow',
};

export function InvoiceDocument({ invoice, client, company, template }: InvoiceDocumentProps) {
  const activeTemplate = { ...fallbackTemplate, ...template };
  const subtotal = invoice.lineItems.reduce((sum, item) => sum + item.amount, 0);
  const taxRate = invoice.taxRate || 0;
  const taxAmount = Number((subtotal * (taxRate / 100)).toFixed(2));
  const total = invoice.total || subtotal + taxAmount;
  const compact = activeTemplate.layout === 'compact';
  const modern = activeTemplate.layout === 'modern';
  const letterhead = activeTemplate.layout === 'letterhead';
  const amount = (value: number) => <CurrencyAmount value={value} currencyCode={invoice.currency || 'USD'} />;

  return (
    <div
      className="invoice-print-area relative mx-auto min-h-[760px] w-full rounded-sm bg-white text-slate-950 shadow-sm"
      style={{
        borderTop: letterhead ? `10px solid ${activeTemplate.primaryColor}` : undefined,
        backgroundImage: template?.letterheadPdfUrl
          ? `linear-gradient(rgba(255,255,255,0.86), rgba(255,255,255,0.86)), url("${template.letterheadPdfUrl}")`
          : undefined,
        backgroundSize: 'cover',
        backgroundPosition: 'center top',
      }}
    >
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 10mm;
          }
          html,
          body {
            margin: 0 !important;
            padding: 0 !important;
            background: white !important;
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          .invoice-print-area {
            width: 100% !important;
            max-width: none !important;
            margin: 0 !important;
            box-shadow: none !important;
            border-radius: 0 !important;
            overflow: visible !important;
            min-height: auto !important;
          }
          .invoice-preview-actions, .no-print {
            display: none !important;
          }
          .invoice-line-items {
            width: 100% !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            page-break-inside: auto !important;
          }
          .invoice-line-items thead {
            display: table-header-group !important;
          }
          .invoice-line-items tfoot {
            display: table-footer-group !important;
          }
          .invoice-line-items tr {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
            page-break-after: auto !important;
          }
          .invoice-line-items td,
          .invoice-line-items th {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
          }
          .invoice-line-items th {
            color: #111827 !important;
            background: #f3f4f6 !important;
            border-bottom: 1px solid #d1d5db !important;
          }
          .invoice-line-items td {
            border-bottom: 1px solid #e5e7eb !important;
          }
          .invoice-totals {
            break-inside: avoid !important;
            page-break-inside: avoid !important;
          }
        }
      `}</style>

      {activeTemplate.watermarkEnabled && activeTemplate.watermarkText && (
        <div className="pointer-events-none absolute inset-0 z-10 flex items-center justify-center">
          <span
            className="select-none text-8xl font-extrabold uppercase"
            style={{
              color: activeTemplate.primaryColor,
              opacity: activeTemplate.watermarkOpacity ?? 0.12,
              transform: 'rotate(-30deg)',
            }}
          >
            {activeTemplate.watermarkText}
          </span>
        </div>
      )}

      {template?.headerImageUrl && (
        <img src={template.headerImageUrl} alt="" className="h-20 w-full object-cover" />
      )}

      <div className={`${compact ? 'p-8' : 'p-10'} relative z-20`}>
        <div
          className={`flex gap-6 ${
            modern ? 'items-start justify-between border-b pb-8' : 'items-start justify-between'
          }`}
          style={{ borderColor: activeTemplate.accentColor }}
        >
          <div className="min-w-0">
            {template?.logoUrl ? (
              <img
                src={template.logoUrl}
                alt=""
                className="mb-4 h-14 max-w-44 object-contain object-left"
              />
            ) : (
              <div
                className="mb-4 flex h-14 w-40 items-center justify-center rounded border text-sm font-semibold"
                style={{ borderColor: activeTemplate.accentColor, color: activeTemplate.primaryColor }}
              >
                LOGO
              </div>
            )}
            <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
              {company?.name || 'Company'}
            </div>
            {activeTemplate.showCompanyAddress && (
              <div className="mt-1 whitespace-pre-line text-sm text-slate-500">
                {company?.address || 'Company address'}
              </div>
            )}
            {activeTemplate.showTaxId && (
              <div className="mt-1 text-sm text-slate-500">Tax ID</div>
            )}
          </div>

          <div
            className={modern ? 'rounded-sm px-5 py-4 text-right text-white' : 'text-right'}
            style={modern ? { backgroundColor: activeTemplate.primaryColor } : undefined}
          >
            <div
              className="text-3xl font-bold tracking-normal"
              style={modern ? undefined : { color: activeTemplate.primaryColor }}
            >
              INVOICE
            </div>
            <div className={modern ? 'mt-2 text-sm text-white/85' : 'mt-2 text-sm text-slate-500'}>
              {invoice.invoiceNumber}
            </div>
            <div className={modern ? 'mt-1 text-sm text-white/85' : 'mt-1 text-sm text-slate-500'}>
              {invoice.status}
            </div>
          </div>
        </div>

        <div className={`grid gap-6 ${compact ? 'mt-8 grid-cols-3 text-sm' : 'mt-10 grid-cols-2'}`}>
          <div>
            <div className="text-xs font-semibold uppercase text-slate-400">Bill To</div>
            <div className="mt-2 font-semibold">{client?.name || 'Client'}</div>
            <div className="mt-1 whitespace-pre-line text-sm text-slate-500">
              {client?.address || 'Client address'}
            </div>
            {client?.email && <div className="mt-1 text-sm text-slate-500">{client.email}</div>}
          </div>
          <div className={compact ? 'text-left' : 'text-right'}>
            <div className="grid gap-1 text-sm">
              <div>
                <span className="text-slate-500">Issue date: </span>
                <span className="font-medium">{format(invoice.issueDate, 'MMM d, yyyy')}</span>
              </div>
              <div>
                <span className="text-slate-500">Due date: </span>
                <span className="font-medium">{format(invoice.dueDate, 'MMM d, yyyy')}</span>
              </div>
              <div>
                <span className="text-slate-500">Currency: </span>
                <span className="font-medium">{invoice.currency || 'USD'}</span>
              </div>
            </div>
          </div>
          {compact && (
            <div>
              <div className="text-xs font-semibold uppercase text-slate-400">Terms</div>
              <div className="mt-2 text-sm text-slate-600">
                {activeTemplate.terms || 'Standard payment terms apply.'}
              </div>
            </div>
          )}
        </div>

        <div className={compact ? 'mt-8' : 'mt-10'}>
          <table className="invoice-line-items w-full border-collapse text-sm">
            <colgroup>
              <col style={{ width: '55%' }} />
              <col style={{ width: '15%' }} />
              <col style={{ width: '15%' }} />
              <col style={{ width: '15%' }} />
            </colgroup>
            <thead>
              <tr
                className="text-white"
                style={{ backgroundColor: activeTemplate.primaryColor }}
              >
                <th className="rounded-tl px-4 py-3 text-left font-semibold">Description</th>
                <th className="px-4 py-3 text-right font-semibold">Qty</th>
                <th className="px-4 py-3 text-right font-semibold">Unit</th>
                <th className="rounded-tr px-4 py-3 text-right font-semibold">Amount</th>
              </tr>
            </thead>
            <tbody>
              {invoice.lineItems.map((line, index) => (
                <tr
                  key={`${line.description}-${index}`}
                  className={index % 2 === 0 ? 'bg-white' : 'bg-slate-50'}
                >
                  <td className="border-x border-b px-4 py-3">{line.description}</td>
                  <td className="border-b px-4 py-3 text-right">{line.quantity}</td>
                  <td className="border-b px-4 py-3 text-right">{amount(line.unitPrice)}</td>
                  <td className="border-r border-b px-4 py-3 text-right font-medium">{amount(line.amount)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="invoice-totals mt-8 flex justify-end">
          <div className="w-full max-w-xs space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-slate-500">Subtotal</span>
              <span>{amount(subtotal)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">Tax {taxRate.toFixed(2)}%</span>
              <span>{amount(taxAmount)}</span>
            </div>
            <div
              className="flex justify-between border-t pt-3 text-lg font-bold"
              style={{ borderColor: activeTemplate.accentColor, color: activeTemplate.primaryColor }}
            >
              <span>Total</span>
              <span>{amount(total)}</span>
            </div>
          </div>
        </div>

        {!compact && (
          <div className="mt-10 grid gap-6 text-sm md:grid-cols-2">
            <div>
              <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
                Payment
              </div>
              <p className="mt-2 text-slate-600">
                {activeTemplate.paymentInstructions || 'Payment instructions will appear here.'}
              </p>
            </div>
            <div>
              <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
                Terms
              </div>
              <p className="mt-2 text-slate-600">
                {activeTemplate.terms || 'Terms and conditions will appear here.'}
              </p>
            </div>
          </div>
        )}

        {invoice.notes && (
          <div className="mt-8 rounded border p-4 text-sm text-slate-600">
            <div className="font-semibold" style={{ color: activeTemplate.primaryColor }}>
              Notes
            </div>
            <p className="mt-2">{invoice.notes}</p>
          </div>
        )}

        <div className="mt-10 border-t pt-4 text-center text-xs text-slate-500">
          {activeTemplate.footerNote || 'Footer note appears here.'}
        </div>
      </div>

      {template?.footerImageUrl && (
        <img src={template.footerImageUrl} alt="" className="h-16 w-full object-cover" />
      )}
    </div>
  );
}
