import * as React from 'react';

const AR_UI_MAP: Record<string, string> = {
  Dashboard: 'لوحة التحكم',
  'Company Overview': 'نظرة عامة على الشركة',
  'Personal Dashboard': 'لوحة التحكم الشخصية',
  'Role View': 'عرض الدور',
  Projects: 'المشاريع',
  Finance: 'المالية',
  Companies: 'الشركات',
  Users: 'المستخدمون',
  Inventory: 'المخزون',
  Purchases: 'المشتريات',
  Clients: 'العملاء',
  Suppliers: 'الموردون',
  Settings: 'الإعدادات',
  'Inventory Management': 'إدارة المخزون',
  'Client Management': 'إدارة العملاء',
  'User Management': 'إدارة المستخدمين',
  'Task Diagram': 'مخطط المهام',
  'Open Tasks': 'المهام المفتوحة',
  Company: 'الشركة',
  Website: 'الموقع الإلكتروني',
  Address: 'العنوان',
  'Position Title': 'المسمى الوظيفي',
  Code: 'الرمز',
  Type: 'النوع',
  'Debit Balance': 'رصيد مدين',
  'Credit Balance': 'رصيد دائن',
  Section: 'القسم',
  Amount: 'المبلغ',
  Source: 'المصدر',
  Description: 'الوصف',
  Debit: 'مدين',
  Credit: 'دائن',
  'Running Balance': 'الرصيد الجاري',
  'Task / Vendor Invoice': 'المهمة / فاتورة المورد',
  'Manual Item': 'عنصر يدوي',
  Qty: 'الكمية',
  'Unit Price': 'سعر الوحدة',
  Remove: 'إزالة',
  Attachments: 'المرفقات',
  Open: 'فتح',
  'Invoice #': 'رقم الفاتورة',
  'Due Date': 'تاريخ الاستحقاق',
  Paid: 'مدفوع',
  Outstanding: 'المتبقي',
  'Purchase Order': 'أمر شراء',
  'Expense Account': 'حساب المصروف',
  Method: 'طريقة',
  'Detail Type': 'نوع التفاصيل',
  Class: 'الفئة',
  Memo: 'مذكرة',
  Lines: 'القيود',
  'Total Debit': 'إجمالي المدين',
  'Total Credit': 'إجمالي الدائن',
  Client: 'العميل',
  Billed: 'مفوتر',
  Ordered: 'مؤكدة',
  'Remaining To Bill': 'المتبقي للفوترة',
  Bucket: 'الفئة',
  Email: 'البريد الإلكتروني',
  Contact: 'جهة الاتصال',
  Invoices: 'الفواتير',
  Visibility: 'الظهور',
  Number: 'الرقم',
  Issued: 'تاريخ الإصدار',
  Due: 'مستحق',
  Template: 'القالب',
  'Origin Tasks': 'المهام الأصلية',
  When: 'الوقت',
  Actor: 'المنفذ',
  Entity: 'الكيان',
  Record: 'السجل',
  Summary: 'الملخص',
  User: 'المستخدم',
  Assignments: 'التعيينات',
  'Primary Role': 'الدور الأساسي',
  Task: 'المهمة',
  Priority: 'الأولوية',
  Assignees: 'المكلفون',
  Supplier: 'المورد',
  Terms: 'الشروط',
  'Purchase Activity': 'نشاط الشراء',
  Document: 'المستند',
  Prefix: 'البادئة',
  Padding: 'عدد الخانات',
  'Next Number': 'الرقم التالي',
  Preview: 'المعاينة',
  'Order #': 'رقم الطلب',
  Dates: 'التواريخ',
  Items: 'العناصر',
  Notes: 'ملاحظات',
  'Issue Date': 'تاريخ الإصدار',
  'Client Name': 'اسم العميل',
  Invoice: 'الفاتورة',
  'Open Receivables': 'الذمم المدينة المفتوحة',
  'Open Payables': 'الذمم الدائنة المفتوحة',
  'Billed This Month': 'المفوتر هذا الشهر',
  'Collected This Month': 'المحصل هذا الشهر',
  'This Month': 'هذا الشهر',
  'Low Stock': 'مخزون منخفض',
  'Out of Stock': 'نفد المخزون',
  Healthy: 'جيد',
  'Incoming Units': 'الوحدات الواردة',
  'Stock Value': 'قيمة المخزون',
  'Tracked Locations': 'المواقع المتتبعة',
  'Recent Stock Movements': 'أحدث حركات المخزون',
  'Revenue vs Collections': 'الإيرادات مقابل التحصيل',
  'Task Load': 'حمولة المهام',
  'Task Status': 'حالة المهام',
  'Finance Exposure': 'التعرض المالي',
  'Action Required': 'إجراء مطلوب',
  'Recent Activity': 'النشاط الأخير',
  'No data available for this chart': 'لا توجد بيانات متاحة لهذا المخطط',
  Date: 'التاريخ',
  Item: 'الصنف',
  Quantity: 'الكمية',
  Reference: 'المرجع',
  Note: 'ملاحظة',
  SKU: 'SKU',
  Category: 'الفئة',
  'On Hand': 'الكمية المتاحة',
  Incoming: 'الوارد',
  Reorder: 'إعادة الطلب',
  'Unit Cost': 'تكلفة الوحدة',
  Vendor: 'المورد',
  Status: 'الحالة',
  Actions: 'الإجراءات',
  Action: 'إجراء',
  Docs: 'ملفات',
  Adjust: 'تعديل',
  Issue: 'صرف',
  Transfer: 'تحويل',
  'Adjust Stock': 'تعديل المخزون',
  'Issue Stock': 'صرف المخزون',
  'Transfer Stock': 'تحويل المخزون',
  'From Location': 'من موقع',
  'To Location': 'إلى موقع',
  Location: 'الموقع',
  Project: 'المشروع',
  'Issued To': 'مُصروف إلى',
  Reason: 'السبب',
  Name: 'الاسم',
  Barcode: 'الباركود',
  Unit: 'الوحدة',
  VAT: 'ضريبة القيمة المضافة',
  'Sale Price': 'سعر البيع',
  'Preferred Supplier': 'المورد المفضل',
  'Create Item': 'إنشاء عنصر',
  'Create Supplier': 'إنشاء مورد',
  'Create Order': 'إنشاء طلب',
  'Create Invoice': 'إنشاء فاتورة',
  'Create User': 'إنشاء مستخدم',
  Save: 'حفظ',
  'Save Adjustment': 'حفظ التعديل',
  Cancel: 'إلغاء',
  Close: 'إغلاق',
  Continue: 'متابعة',
  Search: 'بحث',
  All: 'الكل',
  'Needs Attention': 'تحتاج انتباه',
  Overview: 'نظرة عامة',
  Payables: 'المدفوعات المستحقة',
  Expenses: 'المصروفات',
  'General Ledger': 'دفتر الأستاذ العام',
  Reports: 'التقارير',
  Activity: 'النشاط',
  'Chart of Accounts': 'دليل الحسابات',
  'Journal Entries': 'قيود اليومية',
  'Record Payment': 'تسجيل دفعة',
  'Invoice Preview': 'معاينة الفاتورة',
  'Print / PDF': 'طباعة / PDF',
  'Export CSV': 'تصدير CSV',
  'Export Clients': 'تصدير العملاء',
  'Export Suppliers': 'تصدير الموردين',
  'Export KPIs': 'تصدير المؤشرات',
  'Refresh Reports': 'تحديث التقارير',
  'Choose a company to continue': 'اختر شركة للمتابعة',
  'Select a company to view accounting reports.': 'اختر شركة لعرض تقارير المحاسبة.',
  'Select a company to view management reports.': 'اختر شركة لعرض التقارير الإدارية.',
  'Select a company to view finance analytics.': 'اختر شركة لعرض تحليلات المالية.',
  'No stock movements recorded yet.': 'لا توجد حركات مخزون مسجلة بعد.',
  'No inventory items yet.': 'لا توجد عناصر مخزون بعد.',
  'No inventory': 'لا يوجد مخزون',
  'No orders yet': 'لا توجد طلبات بعد',
  Unassigned: 'غير محدد',
  'No barcode': 'لا يوجد باركود',
  'Non-stock item': 'عنصر غير مخزني',
  'Internal / Unassigned': 'داخلي / غير محدد',
  'Warehouse A': 'المستودع أ',
  'Warehouse B': 'المستودع ب',
  'Select supplier': 'اختر المورد',
  'Search by SKU, item, vendor, or location': 'ابحث حسب SKU أو الصنف أو المورد أو الموقع',
  'Search by order number, supplier, note, or item': 'ابحث برقم الطلب أو المورد أو الملاحظة أو الصنف',
  'Search by invoice number, client, or task': 'ابحث برقم الفاتورة أو العميل أو المهمة',
  'Search by name, contact, email, or phone': 'ابحث بالاسم أو جهة الاتصال أو البريد الإلكتروني أو الهاتف',
  'Search by code, name, detail type, or description': 'ابحث بالرمز أو الاسم أو نوع التفاصيل أو الوصف',
  'Search company...': 'ابحث عن شركة...',
  'No company found.': 'لم يتم العثور على شركة.',
};

const collapse = (value: string) => value.replace(/\s+/g, ' ').trim();

const AR_WORD_MAP: Record<string, string> = {
  account: 'حساب',
  accounts: 'حسابات',
  action: 'إجراء',
  actions: 'إجراءات',
  activity: 'نشاط',
  actor: 'المنفذ',
  add: 'إضافة',
  address: 'العنوان',
  all: 'الكل',
  amount: 'المبلغ',
  apply: 'تطبيق',
  assign: 'تعيين',
  assignments: 'التعيينات',
  assignee: 'المكلّف',
  assignees: 'المكلّفون',
  attachment: 'مرفق',
  attachments: 'مرفقات',
  awaiting: 'بانتظار',
  balance: 'الرصيد',
  billed: 'مفوتر',
  billing: 'الفوترة',
  bucket: 'الفئة',
  cancel: 'إلغاء',
  card: 'بطاقة',
  cash: 'نقد',
  category: 'الفئة',
  chart: 'مخطط',
  client: 'عميل',
  clients: 'عملاء',
  close: 'إغلاق',
  code: 'الرمز',
  collected: 'المحصل',
  company: 'الشركة',
  companies: 'الشركات',
  contact: 'جهة اتصال',
  continue: 'متابعة',
  create: 'إنشاء',
  credit: 'دائن',
  currency: 'العملة',
  date: 'التاريخ',
  dates: 'التواريخ',
  debit: 'مدين',
  default: 'افتراضي',
  delete: 'حذف',
  description: 'الوصف',
  detail: 'تفصيل',
  details: 'تفاصيل',
  diagram: 'المخطط',
  document: 'المستند',
  documents: 'المستندات',
  done: 'مكتملة',
  download: 'تنزيل',
  draft: 'مسودة',
  due: 'الاستحقاق',
  edit: 'تعديل',
  email: 'البريد الإلكتروني',
  entity: 'كيان',
  error: 'خطأ',
  expense: 'مصروف',
  expenses: 'المصروفات',
  export: 'تصدير',
  failed: 'فشل',
  faileds: 'فشلت',
  file: 'ملف',
  files: 'ملفات',
  filter: 'تصفية',
  filters: 'فلاتر',
  finance: 'المالية',
  from: 'من',
  general: 'عام',
  healthy: 'جيد',
  history: 'السجل',
  inactive: 'غير نشط',
  incoming: 'الوارد',
  inventory: 'المخزون',
  invoice: 'فاتورة',
  invoices: 'الفواتير',
  issue: 'صرف',
  issued: 'مصروف',
  item: 'عنصر',
  items: 'عناصر',
  journal: 'دفتر اليومية',
  ledger: 'دفتر الأستاذ',
  line: 'سطر',
  lines: 'سطور',
  loading: 'جاري التحميل',
  location: 'الموقع',
  low: 'منخفض',
  management: 'الإدارة',
  memo: 'مذكرة',
  method: 'طريقة',
  name: 'الاسم',
  net: 'صافي',
  new: 'جديد',
  next: 'التالي',
  no: 'لا',
  note: 'ملاحظة',
  notes: 'ملاحظات',
  number: 'الرقم',
  open: 'مفتوح',
  order: 'طلب',
  orders: 'طلبات',
  ordered: 'مؤكدة',
  outstanding: 'المتبقي',
  overdue: 'متأخرة',
  paid: 'مدفوع',
  payables: 'الذمم الدائنة',
  payment: 'دفعة',
  payments: 'الدفعات',
  position: 'منصب',
  prefix: 'البادئة',
  preview: 'المعاينة',
  price: 'السعر',
  priority: 'الأولوية',
  profile: 'الملف الشخصي',
  project: 'مشروع',
  projects: 'المشاريع',
  purchase: 'شراء',
  purchases: 'المشتريات',
  qty: 'الكمية',
  quantity: 'الكمية',
  receive: 'استلام',
  received: 'مستلم',
  receivables: 'الذمم المدينة',
  record: 'سجل',
  reference: 'مرجع',
  refresh: 'تحديث',
  remove: 'إزالة',
  reorder: 'إعادة الطلب',
  report: 'تقرير',
  reports: 'التقارير',
  revenue: 'الإيرادات',
  role: 'الدور',
  save: 'حفظ',
  search: 'بحث',
  section: 'قسم',
  settings: 'الإعدادات',
  source: 'المصدر',
  status: 'الحالة',
  stock: 'المخزون',
  subtotal: 'الإجمالي الفرعي',
  supplier: 'مورد',
  suppliers: 'الموردون',
  summary: 'الملخص',
  table: 'جدول',
  tag: 'وسم',
  task: 'مهمة',
  tasks: 'المهام',
  this: 'هذا',
  month: 'الشهر',
  template: 'قالب',
  terms: 'الشروط',
  timeline: 'الخط الزمني',
  title: 'العنوان',
  to: 'إلى',
  total: 'الإجمالي',
  totals: 'الإجماليات',
  transfer: 'تحويل',
  type: 'النوع',
  unassigned: 'غير محدد',
  unbilled: 'غير مفوتر',
  unit: 'الوحدة',
  update: 'تحديث',
  upload: 'رفع',
  user: 'مستخدم',
  users: 'المستخدمون',
  vat: 'ضريبة',
  vendor: 'مورد',
  visibility: 'الظهور',
};

function wordFallbackTranslate(text: string): string {
  if (!/[A-Za-z]/.test(text)) return text;
  if (text.length > 140) return text;
  const tokenized = text.split(/(\s+|[/:,#().\-]+)/);
  let changed = false;
  const out = tokenized.map((token) => {
    if (!/[A-Za-z]/.test(token)) return token;
    const lower = token.toLowerCase();
    const translated = AR_WORD_MAP[lower];
    if (!translated) return token;
    changed = true;
    return translated;
  });
  return changed ? out.join('') : text;
}

function isArabicUi() {
  // Primary: read from document.documentElement.lang, which i18n-context keeps in sync
  // with the React language state. This means localizeUiNode re-evaluates correctly
  // whenever components re-render after a language change.
  if (typeof document !== 'undefined') {
    const lang = document.documentElement.lang?.toLowerCase();
    if (lang === 'ar' || lang === 'en') return lang === 'ar';
  }
  // Fallback for SSR / before i18n-context mounts
  try {
    const stored = localStorage.getItem('taskflow_language');
    if (stored === 'en' || stored === 'ar') return stored === 'ar';
  } catch {}
  return false;
}

export function localizeUiText(text: string): string {
  if (!isArabicUi()) return text;
  const normalized = collapse(text);
  if (!normalized) return text;
  return AR_UI_MAP[normalized] ?? wordFallbackTranslate(text);
}

export function localizeUiNode(node: React.ReactNode): React.ReactNode {
  if (!isArabicUi()) return node;
  if (typeof node === 'string') return localizeUiText(node);
  if (Array.isArray(node)) return node.map((entry) => localizeUiNode(entry));
  return node;
}

export function localizeUiPlaceholder(value: unknown): unknown {
  if (typeof value !== 'string') return value;
  return localizeUiText(value);
}
